Fix docker usage during release process
When using the same variable for a docker interaction this error message may
occur.

java.lang.StackOverflowError: Excessively nested closures/functions at com.cloudogu.ces.cesbuildlib.Docker$Image.workAroundEntrypointIssues(Docker.groovy:347) - look for unbounded recursion - call depth: 1025

As the error message does not occur when a different name is used my guess is
that a variable re-usage within the library leads to the stackoverflow.

See also https://stackoverflow.com/questions/50705680/jenkins-pipeline-throws-stackoverflowerror-excessively-nested-closures-functio